# Multi-LLM Chat Models Configuration
# Add new models by editing this file

models:
  # Azure OpenAI Models
  - name: "gpt-4"
    display_name: "GPT-4 (Azure)"
    provider: "azure_openai"
    model_id: "gpt-4"
    capabilities:
      text_input: true
      image_input: true
      image_output: false
      streaming: true
    settings:
      max_tokens: 4000
      temperature: 0.7
      top_p: 1.0
    description: "Most capable GPT-4 model for complex tasks"

  - name: "gpt-4-turbo"
    display_name: "GPT-4 Turbo (Azure)"
    provider: "azure_openai"
    model_id: "gpt-4-turbo"
    capabilities:
      text_input: true
      image_input: true
      image_output: false
      streaming: true
    settings:
      max_tokens: 4000
      temperature: 0.7
      top_p: 1.0
    description: "Faster and cheaper version of GPT-4"

  - name: "gpt-3.5-turbo"
    display_name: "GPT-3.5 Turbo (Azure)"
    provider: "azure_openai"
    model_id: "gpt-35-turbo"
    capabilities:
      text_input: true
      image_input: false
      image_output: false
      streaming: true
    settings:
      max_tokens: 4000
      temperature: 0.7
      top_p: 1.0
    description: "Fast and efficient model for most tasks"

  # Google Gemini Models
  - name: "gemini-pro"
    display_name: "Gemini Pro (Google)"
    provider: "gemini"
    model_id: "gemini-pro"
    capabilities:
      text_input: true
      image_input: false
      image_output: false
      streaming: true
    settings:
      max_tokens: 4000
      temperature: 0.7
      top_p: 1.0
    description: "Google's most capable text model"

  - name: "gemini-pro-vision"
    display_name: "Gemini Pro Vision (Google)"
    provider: "gemini"
    model_id: "gemini-pro-vision"
    capabilities:
      text_input: true
      image_input: true
      image_output: false
      streaming: true
    settings:
      max_tokens: 4000
      temperature: 0.7
      top_p: 1.0
    description: "Gemini with vision capabilities"

  # AWS Claude Models
  - name: "claude-3-opus"
    display_name: "Claude 3 Opus (AWS)"
    provider: "aws_claude"
    model_id: "anthropic.claude-3-opus-20240229-v1:0"
    capabilities:
      text_input: true
      image_input: true
      image_output: false
      streaming: true
    settings:
      max_tokens: 4000
      temperature: 0.7
      top_p: 1.0
    description: "Most intelligent Claude model"

  - name: "claude-3-sonnet"
    display_name: "Claude 3 Sonnet (AWS)"
    provider: "aws_claude"
    model_id: "anthropic.claude-3-sonnet-20240229-v1:0"
    capabilities:
      text_input: true
      image_input: true
      image_output: false
      streaming: true
    settings:
      max_tokens: 4000
      temperature: 0.7
      top_p: 1.0
    description: "Balanced performance and speed"

  - name: "claude-3-haiku"
    display_name: "Claude 3 Haiku (AWS)"
    provider: "aws_claude"
    model_id: "anthropic.claude-3-haiku-20240307-v1:0"
    capabilities:
      text_input: true
      image_input: true
      image_output: false
      streaming: true
    settings:
      max_tokens: 4000
      temperature: 0.7
      top_p: 1.0
    description: "Fastest Claude model"

# Provider Configuration
providers:
  azure_openai:
    api_key_env: "AZURE_OPENAI_API_KEY"
    endpoint_env: "AZURE_OPENAI_ENDPOINT"
    api_version: "2023-12-01-preview"
    
  gemini:
    api_key_env: "GCP_GEMINI_API_KEY"
    
  aws_claude:
    access_key_env: "AWS_ACCESS_KEY_ID"
    secret_key_env: "AWS_SECRET_ACCESS_KEY"
    region_env: "AWS_REGION"